name: terraform-fmt

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/terraform-fmt.yml"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: terraform-fmt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      CHECKPOINT_DISABLE: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.9.8

      - name: Setup reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0

      - name: Terraform fmt check
        run: terraform fmt -check -recursive -diff

      - name: Slack/Teams notification placeholder
        if: always()
        run: echo "Integrate Slack/Teams notification here"
